
# DB connecting properties
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devtest
    username:
    password:
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true